sudo: false

language: node_js

node_js:
  - node

before_install:
  - npm install -g npm@5

install:
  - npm ci

script:
  - npm run test:coveralls
  
after_failure:
  - cat /home/travis/.npm/_logs/2020*
